exports.postApplicationData = {
        area_code: "AC-012",
        first_name: "Bammmym",
        last_name: "Butalidddd",
        birth_date: "2018-02-02",
        age: 22,
        contact_no: "09990371921",
        barangay: "poblacion 1",
        street_address: "6s matiga street",
        city: "Tagbilaran City",
        province: "Bohol",
        religion: "Catholic",
        nationality: "Filipino",
        source_of_income: "OOCL",
        length_of_service: "5 years",
        length_of_stay: "5 years",
        occupation: "Programmer",
        civil_status: "M",
        type_loan: "NEW",
        days_to_pay: 57,
        amount_loan: 3000,
        pay_type: "DAILY",
        pay_breakdown: 60,
        proc_fee: 100,
        Sfirst_name: "Pattt",
        Slast_name: "Butalid",
        Sbirth_date: "2018-02-02",
        Scontact_no: "09123123123",
        Sstreet_address: "Laguna malapit",
        Sbarangay:"poblacion 1",
        Scity: "Laguna city",
        Sprovince: "Laguna Province",
        Sreligion: "Catholic",
        Ssource_of_income: "Sales Manager",
        Snationality: "Filipino"
}
